"""add explore mode columns to runs

Revision ID: 33c38a09fd70
Revises: 1df218b08507
Create Date: 2026-08-15 20:07:27.556699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33c38a09fd70'
down_revision: Union[str, None] = '1df218b08507'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mode', sa.String(), server_default='execute', nullable=False))
        batch_op.add_column(sa.Column('max_actions', sa.Integer(), server_default='25', nullable=False))
        batch_op.add_column(sa.Column('confirmed_non_production', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('generated_bdd_script', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_column('generated_bdd_script')
        batch_op.drop_column('confirmed_non_production')
        batch_op.drop_column('max_actions')
        batch_op.drop_column('mode')

    # ### end Alembic commands ###
